version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

# Tell RTD to use your Conda environment file
conda:
  environment: environment.yml

# Optional: install your package in that environment
python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py